# Generated by Django 3.1.7 on 2021-03-23 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='投稿日時'),
        ),
    ]
